import groovy.json.JsonSlurperClassic

def jsonParse(def json){
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
    agent any

    environment {
        REMOTE_HOST = "64.23.151.32"
        KNOWN_HOSTS_FILE = "${env.WORKSPACE}/known_hosts"
        REMOTE_USER = "" // se llenará dinámicamente desde la credencial
    }

    stages {
        stage('Obtener Usuario SSH y Ruta de Clave') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'PruebaGit', 
                                                   keyFileVariable: 'SSH_KEY', 
                                                   usernameVariable: 'SSH_USER')]) {
                    script {
                        // Mostrar usuario SSH de la credencial
                        echo "Usuario SSH recuperado: ${SSH_USER}"

                        // Mostrar únicamente la ruta temporal de la clave privada
                        echo "Ruta temporal de la clave privada generada: ${SSH_KEY}"
                    }
                }
            }
        }
    }

    post {
        always {
            deleteDir() // limpia workspace
            sh "echo 'Fase Always'"
        }
        success {
            sh "echo 'Fase Success'"
        }
        failure {
            sh "echo 'Fase Failure'"
        }
    }
}
