import groovy.json.JsonSlurperClassic

def jsonParse(def json){
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
    agent any

    environment {
        REMOTE_HOST = "64.23.151.32"
        NEW_KEY_PATH = "/home/" // Ruta donde quieres copiar la clave
    }

    stages {
        stage('Usar Clave SSH en Varios Stages') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'PruebaGit', 
                                                   keyFileVariable: 'SSH_KEY', 
                                                   usernameVariable: 'SSH_USER')]) {
                    script {
                        // Stage 1
                        echo "Usuario SSH: ${SSH_USER}"
                        echo "Ruta temporal: ${SSH_KEY}"
                        
                        sh "echo 'Stage 1 usando la clave en ${SSH_KEY}'"

                        // Copiar la clave a otra ruta
                        sh "cp ${SSH_KEY} ${NEW_KEY_PATH}"
                        sh "chmod 600 ${NEW_KEY_PATH}" // Ajusta permisos para usarla

                        echo "Clave copiada a: ${NEW_KEY_PATH}"

                        // Stage 2
                        echo "Stage 2 reutilizando la misma clave"
                        sh "echo 'Stage 2 usando la clave en ${NEW_KEY_PATH}'"

                        // Stage 3
                        echo "Stage 3 reutilizando la misma clave"
                        sh "echo 'Stage 3 usando la clave en ${NEW_KEY_PATH}'"
                    }
                }
            }
        }
    }
}


